from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.user import User, UserRole
from app.models.sync_queue import SyncQueueItem
from app.services.pipeline import process_sync_queue
from app.core.deps import get_current_user
from app.models.session import SessionEnrollment, TrainingSession
from app.models.certificate import Certificate
from app.models.supervisor import SupervisorSession
from typing import List, Dict, Any
from pydantic import BaseModel

router = APIRouter(prefix="/sync", tags=["Offline Sync"])


class SyncPushPayload(BaseModel):
    items: List[Dict[str, Any]]


@router.post("/push")
def push_offline_data(
    payload: SyncPushPayload,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Receives offline actions (e.g. Trainer creating a session) from the local React Native DB.
    Adds them to SyncQueue and triggers the Pipeline Engine.
    """
    queue_items = []
    for item in payload.items:
        sq_item = SyncQueueItem(
            user_id=current_user.id,
            entity_type=item["entity_type"],
            entity_id=item.get("entity_id"),
            payload=item["payload"],
            device_timestamp=item["device_timestamp"]
        )
        db.add(sq_item)
        queue_items.append(sq_item)
        
    db.commit()
    
    # Process the pipeline -> cascades data to other roles
    process_sync_queue(db, queue_items)
    
    return {"success": True, "processed_items": len(queue_items)}


@router.get("/pull")
def pull_online_data(
    last_sync_timestamp: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Called by React Native when online. 
    Returns data specifically created for the current_user's role since their last sync.
    e.g. If Trainee, returns new SessionEnrollments generated by the Trainer's offline session.
    """
    
    # Dummy structure for now. 
    # Real implementation would query `SessionEnrollment`, `TrainingSession`, `Certificate` 
    # based on cross-role data where `created_at > last_sync_timestamp`.
    response_data = {
        "new_sessions": [],
        "new_enrollments": [],
        "new_certificates": []
    }
    
    from datetime import datetime
    try:
        last_sync = datetime.fromisoformat(last_sync_timestamp.replace('Z', '+00:00'))
    except:
        last_sync = datetime.min
        
    if current_user.role == UserRole.TRAINEE:
        new_enrollments = db.query(SessionEnrollment).filter(
            SessionEnrollment.user_id == current_user.id,
            SessionEnrollment.created_at >= last_sync
        ).all()
        response_data["new_enrollments"] = [e.id for e in new_enrollments]
        
        new_certs = db.query(Certificate).filter(
            Certificate.user_id == current_user.id,
            Certificate.created_at >= last_sync
        ).all()
        response_data["new_certificates"] = [c.certificate_uid for c in new_certs]
        
    elif current_user.role == UserRole.SUPERVISOR:
        new_supervisor_sessions = db.query(SupervisorSession).filter(
            SupervisorSession.supervisor_id == current_user.id,
            SupervisorSession.created_at >= last_sync
        ).all()
        response_data["new_sessions"] = [s.training_session_id for s in new_supervisor_sessions]
        
    return {"success": True, "data": response_data}
